#!/bin/sh

# Check which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)
DARK_FILENAME="wallpaper-dark"
LIGHT_FILENAME="wallpaper"

#if the theme is not dark then we need to switch to it
if [ $THEMEIS != "dark.css" ]; then
    SWITCHTO="-dark"
fi

#set the waybar theme
ln -sf ~/.config/waybar/style/style$SWITCHTO.css ~/.config/waybar/style.css

#set the wofi theme
ln -sf ~/.config/wofi/style/style$SWITCHTO.css ~/.config/wofi/style.css

#set the xfce theme
xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita$SWITCHTO"
xfconf-query -c xsettings -p /Net/IconThemeName -s "Adwaita$SWITCHTO"

#set the GTK theme
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita$SWITCHTO"
gsettings set org.gnome.desktop.interface icon-theme "Adwaita$SWITCHTO"

#change the background image and be cool about it ;)
if [ $SWITCHTO = "-dark" ]; then
    for i in `find ~/.config/hypr/wallpapeurs -type f -name "$DARK_FILENAME.png" -o -name "$DARK_FILENAME.gif" -o -name "$DARK_FILENAME.jpeg" -o -name "$DARK_FILENAME.jpg" -o -name "$DARK_FILENAME.webp" -o -name "$DARK_FILENAME.avif"`;
    do
        BG_SWAP=$i
    done
    
    # swww img ~/.config/hypr/wallpaper-dark.jpeg
else
    for i in `find ~/.config/hypr/wallpapeurs -type f -name "$LIGHT_FILENAME.png" -o -name "$LIGHT_FILENAME.gif" -o -name "$LIGHT_FILENAME.jpeg" -o -name "$LIGHT_FILENAME.jpg" -o -name "$LIGHT_FILENAME.webp" -o -name "$LIGHT_FILENAME.avif"`;
    do
        BG_SWAP=$i
    done
    # swww img ~/.config/hypr/wallpaper.jpeg
fi

if [ $BG_SWAP ]; then
    swww img $BG_SWAP --transition-fps 60 --transition-type wipe --transition-duration 1.5
fi
# swww img ~/.config/hypr/wallpaper$SWITCHTO.jpeg --transition-fps 60 --transition-type wipe --transition-duration 2

#update the sddm image
#ln -sf /usr/share/sddm/themes/sdt/Backgrounds/wallpaper$SWITCHTO.jpg /usr/share/sddm/themes/sdt/wallpaper.jpeg

#restart the waybar
killall -SIGUSR2 waybar
